### ISSUE TITLE
Unhandled exception 

### ISSUE THREAD

**Issue by zachbuchanan** [iTrace-Dev/iTrace-VisualStudio#10]
At writer.writeStartElement("response")

*See attached file for screenshot*

[exception_thrown.zip](https://github.com/iTrace-Dev/iTrace-VisualStudio/files/2384649/exception_thrown.zip)

**Comment by dtg3** [comment]
@cabryant20 @zachbuchanan  is this still an issue on the latest version (should be in Issue-7 branch)? If not, please close.

**Comment by dtg3** [comment]
If the new_design branch is adopted as the head of development for VS Plugin, this issue can be closed.

**Comment by dtg3** [comment]
This needs to be checked in the `fixed_develop` branch. I’d present it needs to be fixed.

**Comment by dtg3** [comment]
I haven't noticed any crashing issues lately from quickly starting and stopping or connecting and disconnecting. I'm closing this issue. If it resurfaces we will open a new issue.
