### ISSUE TITLE
Reticle blocks access to elements under it

### ISSUE THREAD

**Issue by vzyrianov** [iTrace-Dev/iTrace-VisualStudio#12]
Steps to reproduce:
1. Start iTrace Visual Studio
2. Connect to core
3. Display reticle
4. If you move your mouse so the reticle is under it, and try clicking, the click will register to the reticle and not to what is under it. 

For example, normally the cursor will be an I whenever it is over the text section of Visual Studio
![not blocking](https://user-images.githubusercontent.com/15055342/45600118-56c13a80-b9c5-11e8-9f96-6e051072439a.PNG)

However, when the cursor is over the reticle it will become a normal arrow since the cursor is over the reticle and not the editor. 
![blocking](https://user-images.githubusercontent.com/15055342/45600132-90924100-b9c5-11e8-8eea-858c86078de4.PNG)

**Comment by dtg3** [comment]
Reticle feature is no longer present in plugin.
