### ISSUE TITLE
Allow Configuration of Socket Port

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-VisualStudio#14]
It is possible that certain ports may be in use by other end user applications. It is necessary for iTrace Plugins to be able to configure a port number prior to connecting to the Core. 
This feature is directly related to [Core Issue 50](https://github.com/iTrace-Dev/iTrace-Core/issues/50).

**Comment by cabryant20** [comment]
Implemented in issue 7 branch. 
Access via Tools->Options->iTrace

**Comment by dtg3** [comment]
This needs to be done for the `fixed_develop` branch if not already completed.

**Comment by cabryant20** [comment]
Options page to control port number added present in fixed_develop

**Comment by dtg3** [comment]
**Reminder**
We only put **TESTED** features in our mainline development branch (which as discussed in Discord is `fixed_develop`). If an added feature needs verification it should be in a separate branch until verified. Do not rush changes/features into stable branches.

**Comment by cabryant20** [comment]
Verified working with experimental instance and when using installer
