### ISSUE TITLE
Readability and UI Font Colors

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-VisualStudio#17]
UI textbox text is difficult to see when dark theme is used.

**Comment by dtg3** [comment]
@cabryant20 was this fixed? If not, make a note in the wiki detailing that the dark theme will make the plugin difficult to read.

**Comment by shbonita** [comment]
The dark theme will also affect the pupil diameter if that is used as a metric for analysis.

**Comment by dtg3** [comment]
We have not been using the color theme for iTrace presently. Does this need to be added as a new issue to support/detect that later?

**Comment by shbonita** [comment]
No it doesn't need to be because there is nothing we can do on our end.  The researchers need to be aware of that.
