### ISSUE TITLE
Screen Height Value

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-VisualStudio#27]
Using the `fixed_develop` branch the screen height value seems to be recording erroneous screen width dimensions that are not matching the core.

For example on a 1920 x 1080 display, during two separate recording runs the plugin recorded 1040 and then 1160 as the screen height.

**Comment by vzyrianov** [comment]
If the issue is in the outputted XML, then the solution should be to change 
`Screen.PrimaryScreen.WorkingArea` to `Screen.PrimaryScreen.Bounds`

**Comment by cabryant20** [comment]
Committed the change above, screen bounds for plugin match that of core now.
