### ISSUE TITLE
CRITICAL: Visual Studio Plugin Deletes Previously Recorded Data

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-VisualStudio#28]
The iTrace Core plugin will erase the last recorded XML data file if you disconnect and reconnect to the core. Note this is NOT a disconnect during tracking and the plugin is receiving the correct session_start data packets.

Steps to Reproduce:
1) Connect to Core
2) Start Tracking
3) Stop Tracking
4) Disconnect from Core
5) Verify data is in the XML output file
6) Hit Connect to Core
7) Verify all data is gone
8) Hit Disconnect from Core
9) Verify all response data is deleted

**Comment by dtg3** [comment]
This does not seem to occur if you leave the plugin connected and only disconnect once after starting and stopping the tracker multiple times (multiple sessions). Without a source code fix, the only way to resolve the issue is to close and reopen visual studio.

**Comment by cabryant20** [comment]
Latest commit to fixed_develop should allow you to disconnect and reconnect repeatedly. Waiting for someone to verify the fix works for them too before closing issue.

**Comment by cabryant20** [comment]
Verified the steps to reproduce no longer result in previous data being deleted
