### ISSUE TITLE
Add Wiki Page with Documentation

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-VisualStudio#32]
Add documentation, sockets, usage with core, any issues, etc.

**Comment by cabryant20** [comment]
Updated usage info and added how to change sockets. Added installation and data output pages to the wiki. 
Some links will need updated when we post the release. Link to download Core, the link to download iTraceVS.vsix, and the link to the detailed plugin data information in the Core Wiki.

Is there any additional information that needs added?

**Comment by dtg3** [comment]
Consider using paragraphs to represent instruction and ordered list if you are representing ordered instructions. Try to use bullets when it represents and actual unordered list. I’ll look it over more when I’m back home (later tonight).

**Comment by dtg3** [comment]
The basic usage page should probably be similar to the Core basic usage documentation. A brief ordered list and then some extended explanation. Also it's important to hammer home in the documentation that if they do not disconnect the plugin and simply close the IDE, the output data will not be written out properly. @cabryant20 when this is done, let me know.

**Comment by cabryant20** [comment]
Changed so the ordered list is first and simplified. Removed unordered lists and added sections for additional information. Also mentioned the importance of disconnecting before closing in two places.

**Comment by dtg3** [comment]
@cabryant20, be sure to include the valid port range as the settings only have numeric validation. Are there limitations such as connecting, disconnecting, and then changing the port number and connecting again (IE reusing the existing connection versus starting a new one)? If so these need to be documented.

Running an application as admin has two different styles depending if the user is accessing the application from a desktop shortcut vs a start menu shortcut. Describe how this is done.

In `Connecting to the Core` remind users that the Core must be running and the port settings must match. Detail if they have forgotten to run VS in admin mode that the connect to core button will not work (they will forget and at least this will help troubleshoot).

In `Recording Data` the wording sounds like you can record multiple sessions concurrently. This is not the case (that sentence reads odd as well, consider breaking it up). "Starting a new session causes the plugin to finish" sounds vague. Just remove that and say it ends a session and starts a new one.

In `Disconnect from iTrace Core` the sentence "This closes the environment tags of the last plugin output file" is not needed. This is an underlying implementation detail. They simply need to know that it is required and if not done then the output data might not be complete/correct and therefore unusable.

**Comment by dtg3** [comment]
@cabryant20 How is the progress on the documentation changes?

**Comment by clptrsn** [comment]
For the data output files, there is a link to the Core github which is not public facing information.

**Comment by dtg3** [comment]
@clptrsn That content will be made accessible via the webpage when it is copied over. This is the compromise until we open the repos publicly (same with Eclipse).

**Comment by cabryant20** [comment]
What is the full valid range again? Connecting to new sockets works as written, all changes go into effect upon the next connection attempt so disconnecting and then changing ports is proper usage.

For running as admin in two styles do you just mean the difference in Right Click > Run as Admin, compared to Right Click > More > Run as Admin?

Other changes added.

**Comment by dtg3** [comment]
Correct on the right click. People may use either a desktop shortcut or start menu shortcut. Best to have both in the event they are unfamiliar with running applications with Admin privileges.

**Comment by cabryant20** [comment]
Ok, i removed mentioning a specific method in the basic usage and put both in the Opening as Admin section.

**Comment by dtg3** [comment]
Basic content is online. Any additional content additions/modifications will be mentioned in other issues.
