### ISSUE TITLE
Distributable Installer for Plugin

### ISSUE THREAD

**Issue by jmaletic** [iTrace-Dev/iTrace-VisualStudio#6]
Need a stand alone version for distribution.

**Comment by zachbuchanan** [comment]
Issue was with drawing the form with the reticle, standalone starting working when the reticle was taken out.

**Comment by dtg3** [comment]
This requires testing and verification.

**Comment by dtg3** [comment]
@Zealot-311 this will need to be tested with the `new_design` branch as well. Barring any serious issues, that branch will most likely become the new development branch.

**Comment by dtg3** [comment]
This work will need to target the fixed_develop branch.

**Comment by dtg3** [comment]
Installing the plugin using the VSIX generated during a build results in the plugin being installed, but it appears non-functional.

**Comment by dtg3** [comment]
The README now contains information detailing a solution for the release of the VS plugin. This will require additional testing and verification to determine efficacy for clients.

**Comment by dtg3** [comment]
This is done.
