### ISSUE TITLE
Button in menu

### ISSUE THREAD

**Issue by jmaletic** [iTrace-Dev/iTrace-VisualStudio#7]
Start button in menu vs floating window.

**Comment by cabryant20** [comment]
Button in menu working, however it still needs to sync with the floating window button

**Comment by cabryant20** [comment]
![toolmenu](https://user-images.githubusercontent.com/15931084/53195963-cf679b00-35e4-11e9-9b40-0914cad9ffd5.png)

**Comment by shbonita** [comment]
Change Connect to Core to Connect to iTrace-Core and put the awesome logo. 
Can we see a picture of the settings page?

**Comment by dtg3** [comment]
Proposing this feature gets bumped from the EMIP release and moved to a branch for later exploration. While the menu item works properly, synchronizing the menu bar item text has proved to be a time sink with a few odd caveats. I would like to shift full attention to making the window based plugin as solid as possible.

**Comment by dtg3** [comment]
No need to do this. The form window is sufficient and it just introduces extra complexity.

This could be revisited at a later time with a new issue if the need arises.
