### ISSUE TITLE
Incomplete XML Output

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-VisualStudio#9]
If the plugin is connected to iTrace core and recording on the core is stopped and restarted, all but the most recent XML output files will be incomplete (missing closing tags for gazes and plugin elements). Disconnecting the plugin and reconnecting the plugin before starting the next session is the only way to end the open tags.

Propose two conditions for ending XML documents.
1) Plugin is disconnected from Core:
Study is complete and the active XML document can be closed (this currently works).
2) Plugin receives a new location to write out XML:
Study is not complete, but the current recording session is. Close the previous XML document before writing to the new one.

**Comment by dtg3** [comment]
If the new_design branch is adopted as the head of development for VS Plugin, this issue can be closed.

**Comment by dtg3** [comment]
Verify that this issue is not present in `fixed_develop` branch. If issue is present, it must be fixed.

**Comment by cabryant20** [comment]
Verified not present in fixed_develop
